### ISSUE TITLE
Activate Google login functionality on mobile web browser.

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/soop-sok#29]
## Tasks
- [x] **왜 안되는건지 알아보기 (1 hr)**: 다만 문제는 웹 브라우저에서는 잘 되는데 모바일에서는 안 됨. 데스크탑 용에서는 새 탭을 열어서 구글로 연결되서 허락을 받아 오는데 아마 모바일 용에서는 그 새 탭 여는게 용납이 안되는거 같음. -> signInWithPopup 얘를 어떻게 바꾸면 될 것 같은데.
- [x] **레딧에서는 리다이렉트 시켜서 잘 되던데 그걸 참고해보면 좋을 것 같음. (1 hr)**
- [x] **firebase ui 활성화 시키기 (2 hrs)**

## Comments
- 데스크탑 브라우저에서는 기능 제대로 작동함.
- 원인을 찾아내는데 얼마나 걸릴지도 모르기 때문에 예상 시간 도출하기는 좀 어렵지만 그래도 세시간 넘겠나 싶음.
