### ISSUE TITLE
UI work for scrolling messages in the chat window.

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/soop-sok#30]
### Tasks
- [x] messages should start from the top.
- [x] when the total length of messages is longer than the height of the chat window, the scroll should be at the bottom.
- [x] when the scroll of the chat window hits the top, fetch more of the previous messages with lazy loading.
