### ISSUE TITLE
Refactor chat room creation page to include more features.

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/soop-sok#34]
### Tasks
- [x] Add tag section to chat creation page. **(2 hrs)**
- [x] Refactor creation page layout. **(1.5 hrs)**
- [x] Add tag to chat component. **(1 hr)**
