### ISSUE TITLE
Add story feature.

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/soop-sok#36]
## Tasks
- [x] Add send story page **(2 hrs)**
- [x] Add link to the page in features page **(1 hr)**
- [x] Add logic to display stories on banner. **(2 hrs)**
